export default {
    login:{
        name:"",
        address:"",
        photo:"",
        sex:"",
        age:"",
        site:"",
    },
    wallet:{
        private:"",
        public:"",
        address:"",
        backup:false,
        balance:0,
        finger:false
    },
    device:{
        os:"",
        osVersion:"",
        appVersion:"",
        model:"",
        deviceId:"",
        serial:"",
        pushversion:"0001",
        showInvite:false,
        active:true
    },
    currentCoin:{}
};