export default {
    tab_1: require('../images/tab_1.png'),
    tab_1_h: require('../images/tab_1_h.png'),
    tab_2: require('../images/tab_2.png'),
    tab_2_h: require('../images/tab_2_h.png'),
    tab_3: require('../images/tab_3.png'),
    tab_3_h: require('../images/tab_3_h.png'),
    tab_4_h: require('../images/tab_4_h.png'),
    logo: require('../images/logo.png'),
    scan:require('../images/scan.png'),
    my:require('../images/my.png'),
    forward:require('../images/forwad.png'),
    trans:require('../images/trans.png'),
    money:require('../images/money.png'),
    money2:require('../images/money2.png'),
    create_success: require('../images/create_success.png'),
    bg:require('../images/bg.png'),
    ebc:require('../images/ebc.png'),
    in:require('../images/in.png'),
    out:require('../images/out.png'),
    back:require('../images/back.png'),
    kf:require('../images/kf.png'),
    icon_id:require('../images/icon_id.png'),
    right:require('../images/right.png'),
    head:require('../images/head.png'),
    rate:require('../images/rate.png'),
    chat_1:require('../images/chat_1.png'),
    chat_1_h:require('../images/chat_1_h.png'),
    chat_2:require('../images/chat_2.png'),
    chat_2_h:require('../images/chat_2_h.png'),
    chat_3:require('../images/chat_3.png'),
    chat_3_h:require('../images/chat_3_h.png'),
    chat_add:require('../images/chat_add.png'),
    finger:require('../images/finger.png'),
    left:require('../images/left.png'),
    add:require('../images/add.png'),
    search:require('../images/search.png'),
    rem:require('../images/rem.png'),
    invitation_left:require('../images/invitation_left.png'),
    invitation_right:require('../images/invitation_right.png'),
    chat_sign:require('../images/chat_sign.png'),
    chat_group:require('../images/chat_group.png'),
    chat_send:require('../images/chat_send.png'),
    chat_camare:require('../images/chat_camare.png'),
    chat_left:require('../images/chat_left.png'),
    sex0:require('../images/sex0.png'),
    sex1:require('../images/sex1.png'),
    chat_request:require('../images/chat_request.png'),
    group:require('../images/group.png'),
    friend_add:require('../images/friend_add.png'),
    phone:require('../images/phone.png'),
    icon_add:require('../images/icon_add.png'),
    icon_card:require('../images/icon_card.png'),
    icon_dh:require('../images/icon_dh.png'),
    icon_group_add:require('../images/icon_group_add.png'),
    icon_recive:require('../images/icon_recive.png'),
    icon_scan:require('../images/icon_scan.png'),
    icon_trans:require('../images/icon_trans.png'),
    more_w:require('../images/more_w.png'),
    more_b:require('../images/more_b.png'),
    choose:require('../images/choose.png'),
    unchoose:require('../images/unchoose.png'),
    chat_noties:require('../images/chat_noties.png'),
    chat_system:require('../images/chat_system.png'),
    chat_address:require('../images/chat_address.png'),
    r_l:require('../images/r_l.png'),
    r_r:require('../images/r_r.png'),
    huo:require('../images/huo.png'),
    dline:require('../images/dline.png'),
    ts:require('../images/ts.png'),
    hb:require('../images/hb.png'),
    treasure_bg:require('../images/treasure_bg.png'),
    isok:require('../images/isok.png'),
    treasure_banner:require('../images/treasure_banner.png'),
    wallet_top:require('../images/wallet_top.png'),
    create_bg:require('../images/create_bg.png'),
    app_logo:require('../images/app_logo.png'),

    my_set:require('../images/my_set.png'),
    my_help:require('../images/my_help.png'),
    my_fee:require('../images/my_fee.png'),
    my_invite:require('../images/my_invite.png'),
    my_rz:require('../images/my_rz.png'),
    my_about:require('../images/my_about.png'),
    my_info:require('../images/my_info.png'),

    view:require('../images/view.png'),

    commen:require('../images/comm.png'),

    down:require('../images/tx_down.png'),

    up:require('../images/tx_up.png'),

    share_top:require('../images/share_top.png'),
    share_qq:require('../images/share_qq.png'),
    share_wx:require('../images/share_wx.png'),
    share_down:require('../images/share_down.png'),
    time:require('../images/time.png'),
    chat_user:require('../images/chat_user.png'),
    share:require('../images/share.png'),
    share_bg:require('../images/share_bg.png'),
    top_bg:require('../images/top_bg.png'),
  }
  